[ProcParams]
proc1 = ManID,PalletID

[ProcNames]
proc1 = select * from K_WH_PRINT_INCOMEPALLETBARCODE(?,?)

[html]
html = <div class="label ui-resizable ui-droppable" style="-webkit-transform: rotate(90deg);position: relative; background-color: white; height: 9.5cm; width: 6.8cm; font-size: 0.3174603174603175cm; font-family: 'Times New Roman'; text-align: center; top: -1.35cm; left: 1.35cm;">
            <div style="height: 0.8cm; width: 6.8cm; top: 0.5cm; left: 0cm; font-family: 'Times New Roman'; font-size: 0.45cm; text-align: center; position: absolute; overflow: hidden;" class="label ui-resizable ui-droppable ui-draggable">
                <span class="name" style="font-weight:bold;">$d1.ZONENAME</span>
            </div>
            <div style="height: 4.1cm; width: 6.8cm; top: 0.2cm; left: -0.1cm; font-family: 'impact'; font-size: 3.8cm; text-align: center; position: absolute; overflow: hidden;" class="label ui-resizable ui-droppable ui-draggable">
                <span class="name" style="font-weight:200;text-align: right;">$d1.BARCODE1</span>
            </div>
            <div style="height: 2.724867724867725cm; width: 6.8cm; top: 4.3cm; left: 0cm; font-family: 'Free 3 of 9 Extended', 'Free 3 of 9 Extended Regular', 'Free 3 of 9'; font-size: 1.8cm; text-align: center; position: absolute; overflow: hidden;" class="label ui-resizable ui-droppable ui-draggable">
                <span class="name" style="position:relative;font-size:1.6cm;">$d1.PALLET</span>
            </div>
            <div style="height: 4.1cm; width: 6.8cm; top: 5.05cm; left: -0.1cm; font-family: 'impact'; font-size: 3.8cm; text-align: center; position: absolute; overflow: hidden;" class="label ui-resizable ui-droppable ui-draggable">
                <span class="name" style="font-weight:200;text-align: right;">$d1.BARCODE2</span>
            </div>
            <div style="height: 0.35cm; width: 3cm; top: 9cm; left: 3.7cm; font-family: 'Times New Roman'; font-size: 0.25cm; text-align: right; position: absolute; overflow: hidden;" class="label ui-resizable ui-droppable ui-draggable">
                <span class="name" style="font-weight:bold;">$d1.EMPL</span>
            </div>
            <div style="height: 0.35cm; width: 1.2cm; top: 9cm; left: 2.5cm; font-family: 'Times New Roman'; font-size: 0.25cm; text-align: center; position: absolute; overflow: hidden;" class="label ui-resizable ui-droppable ui-draggable">
                <span class="name">
                    #if $d1.DETAIL >= 1
                        копия
                    #end if
                </span>
            </div>
            <div style="height: 0.35cm; width: 2.5cm; top: 9cm; left: 0cm; font-family: 'Times New Roman'; font-size: 0.25cm; text-align: center; position: absolute; overflow: hidden;" class="label ui-resizable ui-droppable ui-draggable">
                <span class="name" style="font-weight:bold;">
                    #from time import localtime, strftime
                    $strftime("%d.%m.%Y %H:%M:%S", $localtime())
                </span>
            </div>
        </div>

[ProcDataList]
proc1 = d1

[ProcFetches]
proc1 = one

